name: Update Msnps_hg38 VCF Reference File

on:
  schedule:
    - cron: '0 0 * * 0' # רץ בכל יום ראשון בחצות
  workflow_dispatch: # מאפשר הרצה ידנית

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get current date
        id: date_step
        run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT
        
      - name: Download latest HG38 CSV
        run: |
          curl -L -o snps_hg38.csv https://ybrowse.org/gbrowse2/gff/snps_hg38.csv

      - name: Run conversion script
        run: |
          python additions/from_snpsCSV_to_Msnps_VCF.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: Msnps_hg38.vcf.gz
          tag_name: required_large_files
          body: "Updated Msnps_hg38 VCF based on latest data from ybrowse. Date: ${{ steps.date_step.outputs.date }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
